- hosts: datanode2
  tasks:
  - name: "copying java..."
    copy:
     src: "/root/Ansible_playbooks/jdk-8u171-linux-x64.rpm"
     dest: "/"
  - name: "copying hadoop..."
    copy:
     src: "/root/Ansible_playbooks/hadoop-1.2.1-1.x86_64.rpm"
     dest: "/"
  - name: "installing java..."
    package:
     name: "/jdk-8u171-linux-x64.rpm"
     state: present
  - name: "setting up path variable..."
    lineinfile:
     path: "/root/.bashrc"
     insertafter: "EOF"
     line: "{{ item }}"
    with_items:
    - "export JAVA_HOME=/usr/java/jdk1.8.0_171-amd64/"
    - "export PATH=/usr/java/jdk1.8.0_171-amd64/bin/:$PATH"
  - name: "installing hadoop..."
    command: "rpm -ivh /hadoop-1.2.1-1.x86_64.rpm --force"    

 
