- hosts: tasktracker
  vars_prompt:
  - name: "ip"
    prompt: "enter jobtackaer ip..."
    private: false
  tasks:
  - name: "copying mapred-site.xml..."
    copy: 
     src: "/etc/hadoop/mapred-site.xml"
     dest: "/etc/hadoop/mapred-site.xml"
  - name: "setting up mapred-site.xml..."
    lineinfile:
     path: "/etc/hadoop/mapred-site.xml"
     regexp: "^<value>"
     line: "<value>{{ ip }}:9002</value>"
  - name: "starting task tracker..."
    command: "hadoop-daemon.sh start tasktracker"
